const express = require('express');
const router = express.Router();
const messageController = require('../controllers/messageController');
const { verifyUserToken } = require('../utils/authMiddleware');
router.post('/', verifyUserToken, messageController.sendMessage);
router.get('/history/:otherUserId', verifyUserToken, messageController.getMessageHistory);
router.patch('/:messageId/read', verifyUserToken, messageController.markAsRead);
router.post('/:messageId/reply', verifyUserToken, messageController.replyToMessage);
router.post('/sendToAdmin', verifyUserToken,messageController.sendMessageToAdmin);
module.exports = router;
